### ISSUE TITLE
Backend

### ISSUE THREAD

**Issue by JPSchellenberg** [Squarelet/squarelet#14]
Hi,

in your roadmap, I saw that you are planning to provide a backend (simple backend options). Which Tech-Stack are you planning to use and what functions do you want to provide? Do you have any plans that you could share, so I can have a look at how I might help you?

Best,
JP

**Comment by aivuk** [comment]
Right now we only have in the backend Postgresql as the database and a RESTful API endpoint using [PostgREST](http://postgrest.org/), for the user accounts management and to have boards stored on the server. PostgREST is a compiled  Haskell program, I don't know if there is an already compiled version for RaspeberryPi. Later, for the real time board synchronization we will have some WebSocket server, probably  [ws](https://github.com/websockets/ws).
